# Generated by Django 5.2.1 on 2025-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='district',
            field=models.CharField(choices=[('Islands', 'Islands'), ('Kwai Tsing', 'Kwai Tsing'), ('North', 'North'), ('Sai Kung', 'Sai Kung'), ('Sha Tin', 'Sha Tin'), ('Tai Po', 'Tai Po'), ('Tsuen Wan', 'Tsuen Wan'), ('Tuen Mun', 'Tuen Mun'), ('Yuen Long', 'Yuen Long'), ('Central and Western', 'Central and Western'), ('Eastern', 'Eastern'), ('Kowloon City', 'Kowloon City'), ('Yau Tsim Mong', 'Yau Tsim Mong'), ('Sham Shui Po', 'Sham Shui Po'), ('Wan Chai', 'Wan Chai'), ('Southern', 'Southern'), ('Wong Tai Sin', 'Wong Tai Sin'), ('Kwun Tong', 'Kwun Tong')], max_length=50),
        ),
    ]
